### ISSUE TITLE
Seaglide upgrades not downloadable

### ISSUE THREAD

**Issue by SupsDude** [RamuneNeptune/SubnauticaMods#1]
Cam't download seaglide upgrades. Was the link removed?

**Comment by RamuneNeptune** [comment]
Not released yet, only available for Beta testing in the [Subnautica Modding](https://discord.gg/UpWuWwq) discord server

**Comment by RamuneNeptune** [comment]
Specifically this channel 
![image](https://user-images.githubusercontent.com/94365980/212466069-61137300-dfbc-447f-8b3b-e1b74747c4b9.png)
